### ISSUE TITLE
Show a message like "made with :heart: by [author]" at the end of the page

### ISSUE THREAD

**Issue by etrapero** [crisgruiz/Electrike#8]
As a Electrike user,
I want to see who made the webapp
so that I can hire the developer

Notes:
It is probably a good idea to add a link to the Github repository of the project

Links: 
- https://gist.github.com/oliveratgithub/7192c585ce6850692199036d46d3dade

**Comment by crisgruiz** [comment]
You can already see who made the webapp with a link to my Github profile.  Also, you can find the link to the Github repository of the project (github icon)
